/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/meshes/secondFloor.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function SecondFloor(props) {
  const { nodes, materials } = useGLTF('/meshes/secondFloor.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube001.geometry} material={materials.wire_177088027} />
      <mesh geometry={nodes.Cube001_1.geometry} material={materials.letter_box} />
      <mesh geometry={nodes.Cube001_2.geometry} material={materials['fxt_J03_red_chair:lambert2SG']} />
      <mesh geometry={nodes.Cube001_3.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.Cube001_4.geometry} material={materials.Door_material} />
      <mesh geometry={nodes.Cube001_5.geometry} material={materials.Handle_material} />
      <mesh geometry={nodes.Cube001_6.geometry} material={materials.Window_material} />
      <mesh geometry={nodes.Cube001_7.geometry} material={materials.Glass_material} />
      <mesh geometry={nodes.Cube001_8.geometry} material={materials.Plastic_Handle_material} />
      <mesh geometry={nodes.Cube001_9.geometry} material={materials.Sill_material} />
      <mesh geometry={nodes.Cube001_10.geometry} material={materials.white_walls} />
      <mesh geometry={nodes.Cube001_11.geometry} material={materials.Simple_Ceiling_Fan} />
      <mesh geometry={nodes.Cube001_12.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Cube001_13.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube001_14.geometry} material={materials['fxt_J03_red_chair:Metal_BrushedSG']} />
      <mesh geometry={nodes.Cube001_15.geometry} material={materials['fxt_J03_red_chair:lambert3SG']} />
      <mesh geometry={nodes.Cube001_16.geometry} material={materials.wire_225087143} />
      <mesh geometry={nodes.Cube001_17.geometry} material={materials.top_lights} />
      <mesh geometry={nodes.Cube001_18.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Cube001_19.geometry} material={materials.white_wall_classroom} />
      <mesh geometry={nodes.Cube001_20.geometry} material={materials.yellow_part_of_wall} />
      <mesh geometry={nodes.Cube001_21.geometry} material={materials['Material.005']} />
      <mesh geometry={nodes.Cube001_22.geometry} material={materials.smoke_dec} />
      <mesh geometry={nodes.Cube001_23.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.Cube001_24.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.Cube001_25.geometry} material={materials['Material.010']} />
      <mesh geometry={nodes.Cube001_26.geometry} material={materials['Material.011']} />
      <mesh geometry={nodes.Cube001_27.geometry} material={materials['Material.012']} />
      <mesh geometry={nodes.Cube001_28.geometry} material={materials.None} />
      <mesh geometry={nodes.Cube001_29.geometry} material={materials.bench_wood} />
      <mesh geometry={nodes.Cube001_30.geometry} material={materials.bench_legs} />
      <mesh geometry={nodes.Cube001_31.geometry} material={materials['Material.013']} />
      <mesh geometry={nodes.Cube001_32.geometry} material={materials['Material.007']} />
    </group>
  )
}

useGLTF.preload('/meshes/secondFloor.glb')
